name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install treesitter-cli
      run: cargo install tree-sitter-cli
    - name: generate parser
      run: tree-sitter generate
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
